### ISSUE TITLE
Como reportar problemas na base de dados?

### ISSUE THREAD

**Issue by luizirber** [voltdatalab/Atlas-Analytics#2]
Olá!

Inspirado [nesse artigo](http://trasel.com.br/usando-sql-lite-para-encontrar-os-desertos-de-noticias-no-brasil/) escrevi a análise usando um Jupyter notebook e `pandas` no seguinte repositório:
https://github.com/luizirber/2018-desertos ([link direto para o notebook](https://github.com/luizirber/2018-desertos/blob/master/Usando%20Pandas%20para%20encontrar%20os%20desertos%20de%20not%C3%ADcias%20no%20Brasil.ipynb)). Encontrei algumas inconsistências que parecem vir das fontes usadas para gerar a base de dados, mas não sei qual o local correto para reportar erros. Para vocês? Para as fontes originais?

Sugestões?

P.S: ótimo trabalho!

**Comment by sergiospagnuolo** [comment]
pode ser por aqui. Por favor, crie uma issue nova relatando qual a inconsistência.
